version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres
    environment:
      POSTGRES_DB: postdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
